### ISSUE TITLE
Unable to deploy uaa-release

### ISSUE THREAD

**Issue by rkoster** [cppforlife/bosh-provisioner#10]
While trying to deploy uaa-release with `vagrant-bosh` I encountered the following error:
```
Error: Provisioning deployment: Starting instance: Updating instance 0: Applying: Compiling templates bosh: Compiling templates: Rendering config/uaa.yml ERB: Running ruby: Runni
ng command: 'ruby /tmp/erb-render.rb /tmp/erb-context.json /tmp/tar-CmdExtractor401847581/templates/uaa.yml.erb /tmp/instance-templatescompiler-RenderedArchivesCompiler844750026/
uaa/config/uaa.yml', stdout: '', stderr: '/tmp/erb-render.rb:140:in `rescue in render': Error filling in template '/tmp/tar-CmdExtractor401847581/templates/uaa.yml.erb' for bosh/
0 (line 352: #<NameError: uninitialized constant TemplateEvaluationContext::YAML>) (RuntimeError)
        from /tmp/erb-render.rb:126:in `render'
        from /tmp/erb-render.rb:151:in `<main>'
': exit status 1
```

Apparently the [`uaa.yml.erb`](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/uaa.yml.erb#L549) template assumes the `YAML` class is available.

**Comment by rkoster** [comment]
already seems to be fixed in https://github.com/cppforlife/bosh-provisioner/commit/ba448aaa0916195b469915dd3139bb8fbc63523e
